version: "2"
services:
  # user-service:
  #     depends_on: 
  #         - user-database
  #     container_name: user_auth_service
  #     build: ./user_auth_service
  #     ports:
  #         - "8082:8080"
  user-database:
      container_name: user_auth_service_postgres
      image: postgres
      ports:
          - "5433:5432"
      environment: 
          - POSTGRES_PASSWORD=password
          - POSTGRES_USER=postgres
    #   volumes:
          # - ./user_auth_service/db_init/init.sh:/docker-entrypoint-initdb.d/init.sh
        #   - ./user_auth_service/db_init/dataload/dataload.sql:/docker-entrypoint-initdb.d/dataload.sql
  todo-database:
      container_name: todo_service_postgres
      image: postgres
      ports:
          - "5434:5432"
      environment: 
          - POSTGRES_PASSWORD=password
          - POSTGRES_USER=postgres
      volumes:
          # - ./todo_service/db_init/init.sh:/docker-entrypoint-initdb.d/init.sh
          - ./todo_service/db_init/dataload/dataload.sql:/docker-entrypoint-initdb.d/dataload.sql

  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

          